encoder:
    n_conv: 3
    n_resblock: 4
    channels: 64

decoder:
    n_conv: 3
    n_resblock: 4
    channels: 64

discriminator:
    n_conv: 4
    channels: 64
    gan_type: lsgan
    n_scale: 3

loss:
    L1_loss: 10
    L1_loss_CC: 10
    gan: 1
    KL_loss: 0.01
    KL_loss_CC: 0.01

learning:
    batch_size: 2
    image_size: 256
    learning_rate: 0.0001
    beta1: 0.5
    beta2: 0.999
    n_iter: 1000000
    summary: 50
    checkpoint_steps: 1000
    
path:
    experiment: horse2zebra
    data_root_path: datasets/horse2zebra
    outputs: outputs

